name: gradle-release-build-jar-and-linux

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install graalvm
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '21.3.0.java11'
      - name: Install native-image
        run: gu install native-image
      - name: Build jvm jar
        run: ./gradlew -PprojVersion="${{ github.event.release.tag_name }}" build
      - name: Upload jvm
        id: upload-jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/libs/http-live-log-${{ github.event.release.tag_name }}.jar
          asset_name: http-live-log-${{ github.event.release.tag_name }}.jar
          asset_label: jar
          asset_content_type: application/octet-stream
      - name: Build native executable
        run: ./gradlew -PprojVersion="${{ github.event.release.tag_name }}" build -Dquarkus.package.type=native
      - name: Upload native executable
        id: upload-native-executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/http-live-log-${{ github.event.release.tag_name }}-runner
          asset_name: http-live-log-${{ github.event.release.tag_name }}-linux
          asset_label: linux
          asset_content_type: application/octet-stream